config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/index'
  root to: "home#index"

  devise_for :users

  resources :articles do
    resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :favorites

  #existsの使い方
  # Articleモデルにユーザがいいねしているかを判定するメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :favorites
  # Userがファボした記事
  has_many :favorite_articles, through: :favorites, source: :article

  #=====================自分がフォローしているユーザとの関連=======================
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  #=======================================================================

  #====================自分がフォローされるユーザとの関連=========================
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  #=======================================================================

  validates :username, uniqueness: true, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index]
    before_action :configure_permitted_parameters, if: :devise_controller?

    #　新規登録及びログイン後に記事一覧画面に遷移
    def after_sign_in_path_for(resource)
      if current_user
        flash[:notice] = "ログインに成功しました" 
        articles_path#　指定したいパスに変更
      else
        flash[:notice] = "新規登録完了しました。次に名前を入力してください" 
        articles_path  #　指定したいパスに変更
      end
    end

    #　deviseのストロングパラメータ設定
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
      @articles = Article.all
    end

    def new
      @article = Article.new
    end

    def create
			@article = Article.new(article_params)
			@article.user_id = current_user.id
			@article.save
			redirect_to articles_path
    end

		def show
      @article = Article.find(params[:id])
      @user = @article.user
		end

		def edit

		end
		

    def update

    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
    end

    private
			def article_params
				params.require(:article).permit(:body,:title)
			end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.new(article_id: params[:article_id])
    favorite.save
    @article = Article.find(params[:article_id])
    redirect_to article_path(@article.id)
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:article_id])
    favorite.destroy
    @article = Article.find(params[:article_id])
    redirect_to article_path(@article.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @follow = current_user.active_relationships.new(follower_id: params[:user_id])
    @follow.save
    redirect_to users_path
  end

  def destroy
    @follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    @follow.destroy
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
    @favorite_articles = @user.favorite_articles
  end

  def follows
    @user = User.find(params[:id])
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    @user = User.find(params[:id])
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-8 offset-2 mb-3">
			<h1>記事一覧</h1>
		</div>
		<div class="col-8 offset-2">
			<% @articles.each do |article| %>
				<%= link_to article.title, article_path(article.id) %>
				<hr>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="container">
	<%= form_with model: @article do |form| %>
		<div class="row">
			<div class="col-6 offset-3">
				<div class="form-group mt-3">
					<%= form.label :title, "タイトル", class: "mb-1" %>
					<%= form.text_field :title, class: 'form-control' %>
				</div>
				<div class="form-group mt-3">
					<%= form.label :body, "本文", class:"mb-1" %>
					<%= form.text_area :body, size: "60x10",class: 'form-control' %>
				</div>
				<div class="form-group mt-3">
					<%= form.submit "投稿する", class: 'btn-btn-primary' %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3 mt-3">
      <h2 class="d-inline"><%= @article.title %></h2>

      <% if @article.favorited_by?(current_user) %>
        <%= link_to article_favorites_path(@article.id), method: :delete do %>
          <i class="fas fa-heart unlike-btn"></i>
        <% end %>
      <% else %>
        <%= link_to article_favorites_path(@article.id), method: :post do %>
          <i class="far fa-heart like-btn"></i>
        <% end %>
      <% end %>
      <%= @article.favorites.count %>

      <% if current_user.id == @user.id %>
        <%= link_to "削除", article_path(@user.id), method: :delete, class: "pt-2 float-right" %>
      <% end %>
      <hr>
      <%= link_to @user.username, user_path(@user.id) %>

      <% if @user.id != current_user.id %>
        <% if @user.followed_by?(current_user) %>
          <%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "text-muted" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "text-muted" %>
        <% end %>
      <% end %>

        <p class="article-body mt-4"><%= @article.body %></p>
    <div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>ようこそChillForumへ</h1>
      <p>気軽に記事を投稿してみてください</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChillBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/navigation_bar' %>
          <div class="my-3">
          </div>
        </div>
      </div>
    </div>
     <%= yield %>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/shared/_navigation_bar.html.erb
<header>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <%= link_to "ChillForum", root_path, class: 'navbar-brand' %>
    <div id="Navber">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to '投稿する', new_article_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to '記事一覧', articles_path, class: 'nav-link' %>
          </li>
      <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/users/followers.html.erb
<div class="container"> 
  <div class="row">
    <div class="col-8 offset-2">
      <div class="col-6">
        <div class="lead">
          <%= @user.username %>
        </div>
      </div>
      <div class="col">
        <% if @user.id != current_user.id %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "float-right" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "float-right" %>
          <% end %>
        <% end %>
      </div>
      <div class="col mb-4">
        <%= link_to "#{@user.active_relationships.count} フォロー", follows_user_path(@user.id) %>
        <%= link_to "#{@user.passive_relationships.count} フォロワー", followers_user_path(@user.id) %>
      </div>
    </div>

    <hr>

    <div class="col-6 offset-3">
      <% @users.each do |user| %>
        <hr>

        <%= link_to user.username, user_path(user.id) %>

        <% if current_user != user.id %>
          <% if user.followed_by?(current_user) %>
            <%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: "float-right" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "float-right" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="col-6">
        <div class="lead">
          <%= @user.username %>
        </div>
      </div>
      <div class="col">
        <% if @user.id != current_user.id %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "float-right" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "float-right" %>
          <% end %>
        <% end %>
      </div>
      <div class="col mb-4">
        <%= link_to "#{@user.active_relationships.count} フォロー", follows_user_path(@user.id) %>
        <%= link_to "#{@user.passive_relationships.count} フォロワー", followers_user_path(@user.id) %>
      </div>
    </div>

    <hr>

    <div class="col-6 offset-3 mt-5">
      <% @users.each do |user| %>
        <%= link_to user.username, user_path(user.id) %>

        <% if current_user != user.id %>
          <% if user.followed_by?(current_user) %>
            <%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: "float-right" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "float-right" %>
          <% end %>
        <% end %>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <p>ユーザ一覧</p>
    </div>
    <div class="col-8 offset-2">
      <% @users.each do |user| %>  
        <%= link_to user.username, user_path(user.id) %>
      <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="col-6">
        <div class="lead">
          <%= @user.username %>
        </div>
      </div>
      <div class="col">
        <% if @user.id != current_user.id %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "float-right" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: :"float-right" %>
          <% end %>
        <% end %>
      </div>
      <div class="col mb-3">
        <%= link_to "#{@user.active_relationships.count} フォロー", follows_user_path(@user.id) %>
        <%= link_to "#{@user.passive_relationships.count} フォロワー", followers_user_path(@user.id) %>
      </div>

      <hr>
      <div class="col mb-3">
        <p>投稿記事</p>
        <% @articles.each do |article| %>
          <%= link_to article.title, article_path(article.id) %>
          <hr>
        <% end %>
      </div>
      <div class="col">
        <p>いいねした記事:
          <% @favorite_articles.each do |favorite_article| %>
            <hr>
            <p><%= link_to favorite_article.title, article_path(favorite_article.id) %></p>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>